"""
Interactive Onboarding & Setup Wizard for QA / Jira Automation Tool.
Configures Jira, Gemini AI key, Test Execution (TE) defaults, and launches initial session login.
"""
import os
import sys

import config


def run_setup():
    print("\n========================================================")
    print("      Welcome to QA / Jira Automation Setup Wizard       ")
    print("========================================================\n")
    print("This wizard will configure your Jira settings, Gemini API key,")
    print("and default Test Execution (TE) structure.\n")

    # Load existing env values or defaults
    current_jira_url = os.getenv("JIRA_BASE_URL", config.JIRA_BASE_URL)
    current_jira_user = os.getenv("JIRA_USERNAME", config.JIRA_USERNAME)
    current_project = os.getenv("PROJECT_KEY", config.PROJECT_KEY)
    current_issue_type = os.getenv("DEFECT_ISSUE_TYPE", config.DEFECT_ISSUE_TYPE)
    current_gemini_key = os.getenv("GEMINI_API_KEY", "")
    current_gemini_model = os.getenv("GEMINI_MODEL", config.GEMINI_MODEL)
    current_te_key = os.getenv("DEFAULT_TE_KEY", config.DEFAULT_TE_KEY)
    current_title_pattern = os.getenv("DEFECT_TITLE_PATTERN", config.DEFECT_TITLE_PATTERN)

    # 1. Jira Connection
    print("\n--- [1/4] Jira Instance Settings ---")
    jira_url = input(f"Jira Base URL [{current_jira_url}]: ").strip() or current_jira_url
    jira_url = jira_url.rstrip("/")
    jira_user = input(f"Jira Username [{current_jira_user}]: ").strip() or current_jira_user
    project_key = input(f"Jira Project Key [{current_project}]: ").strip() or current_project
    issue_type = input(f"Defect Issue Type [{current_issue_type}]: ").strip() or current_issue_type

    # 2. Gemini AI
    print("\n--- [2/4] Google Gemini AI Settings ---")
    gemini_key = input(f"Gemini API Key [{'...' + current_gemini_key[-6:] if len(current_gemini_key) > 6 else 'Not set'}]: ").strip() or current_gemini_key
    gemini_model = input(f"Gemini Model [{current_gemini_model}]: ").strip() or current_gemini_model

    # 3. TE & Customization
    print("\n--- [3/4] Test Execution (TE) & Customization ---")
    default_te = input(f"Default Test Execution (TE) Key [{current_te_key}]: ").strip() or current_te_key
    print("\nDefect Title Format Pattern:")
    print("Available variables: {TE_KEY}, {TC_KEY}, {AI_TITLE}")
    print("Example result: '[TE-101][TC-123] Login button unresponsive'")
    title_pattern = input(f"Pattern [{current_title_pattern}]: ").strip() or current_title_pattern

    # 4. Save to .env file
    env_content = f"""# Auto-generated by setup.py
JIRA_BASE_URL={jira_url}
JIRA_USERNAME={jira_user}
PROJECT_KEY={project_key}
DEFECT_ISSUE_TYPE={issue_type}

GEMINI_API_KEY={gemini_key}
GEMINI_MODEL={gemini_model}

DEFAULT_TE_KEY={default_te}
DEFECT_TITLE_PATTERN={title_pattern}
"""

    with open(".env", "w", encoding="utf-8") as f:
        f.write(env_content)

    print("\n[SUCCESS] Configuration saved to '.env'.")

    # 5. Jira Session Login
    print("\n--- [4/4] Jira Browser Session Initialization ---")
    do_login = input("Would you like to perform the one-time Jira browser login now? [Y/n]: ").strip().lower()
    if do_login in ("", "y", "yes"):
        try:
            import jira_actions
            jira_actions.login_and_save_session()
        except Exception as e:
            print(f"[!] Login error: {e}")
            print("You can run 'python jira_actions.py' anytime later to log in.")
    else:
        print("Skipped browser login. You can run 'python jira_actions.py' anytime to log in.")

    print("\n========================================================")
    print(" Setup Complete! You can now run:")
    print(f"   python main.py --te {default_te} TC-123")
    print("========================================================\n")


if __name__ == "__main__":
    run_setup()
